databaseChangeLog:
  - changeSet:
      id: 00.001.00/ddl/schema
      author: RKhabirov
      changes:
        - tagDatabase:
            tag: release/00.001.00

        - sql:
            sql: create schema if not exists food
            endDelimiter: ;

        - rollback:
            sql: drop schema if exists food cascade
            endDelimiter: ;
