server:
  port: 8080
  enabled: true

spring:
  application:
    name: notion-back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=notion
    username: postgres
    password: example
    hikari:
      pool-name: HikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 1
      idle-timeout: 200000
      minimum-idle: 1
      schema: notion
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      format_sql: true
      generate_statistics: true
      show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true

logbook:
  strategy: default
  exclude:
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**
  format:
    style: json
  body:
    max-size: 3000
    filters:
      string: token
      number: number
  headers:
    enabled: false
  logger:
    active: true

notion:
  proxy:
    schema: http
    host: localhost
    port: 8081
    basePath: /v1/rest/{partner}
    max-total-connections: 30
    max-default-per-route-connections: 30
    retry-max-attempts: 1
    retry-delay: 5000
    ssl:
      enabled: false
      client-auth: need
      key-store: proxy-keystore.p12
      key-alias: server
      key-store-type: PKCS12
      key-store-password: example
      trust-store: proxy-truststore.p12
      trust-store-type: PKCS12
      trust-store-password: example
    paths:
      get-deck: /getDeck
      get-decks: /getDecks

anki:
  proxy:
    schema: http
    host: localhost
    port: 8082
    basePath: /v1/rest/{partner}
    max-total-connections: 30
    max-default-per-route-connections: 30
    retry-max-attempts: 1
    retry-delay: 5000
    ssl:
      enabled: false
      client-auth: need
      key-store: proxy-keystore.p12
      key-alias: server
      key-store-type: PKCS12
      key-store-password: example
      trust-store: proxy-truststore.p12
      trust-store-type: PKCS12
      trust-store-password: example
    paths:
      get-deck: /getDeck
      get-decks: /getDecks

notion-back:

build:
  version: @project.version@
