server:
  port: 8080
  enabled: true

spring:
  application:
    name: notion-back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=notion
    username: postgres
    password: example
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
build:
  version: @project.version@
